pr_days_tracker/pr_days_tracker/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('tracker_app.urls')),
    path('nprtdportal/', admin.site.urls),
]

pr_days_tracker/tracker_app/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('signup/', views.signup_view, name="signup"),
    path('otp/', views.otp_view, name="request_otp"),
    path('profile/', views.profile_view, name="profile"),
    path('dashboard/', views.dashboard_view, name="dashboard"),
    path('deactivate/', views.deactivate_account, name="deactivate"),
    path('travel/', views.travel_date_view, name="travel"),
    path('how/', views.how_to_view, name="how"),
    path('autonotify/', views.send_email_notifications, name="notify"),
    url(r'^profile/*', views.profile_view, name="profile_action"),
    url(r'^travel/(?P<form_action>[a-z]+)/(?P<row_id>[0-9]+)', views.travel_date_view, name="travel_action"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

pr_days_tracker/tracker_app/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField


# Create your models here.

class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):

    username = None
    email = models.EmailField(_('email'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()


class UserCountryData(models.Model):

    entry_date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # country_name = models.CharField(max_length=5, help_text='Select Country to monitor')
    country_name = CountryField()
    reminder_interval = models.CharField(default='3 M', max_length=4)
    pr_date = models.DateField(blank=True, null=True)
    notifications_on = models.BooleanField(default=True)

    class Meta:
        unique_together = ['country_name', 'user']

    def __str__(self):
        return "%s" % self.user


class TravelData(models.Model):

    country_name = CountryField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    entry_date = models.DateField()
    exit_date = models.DateField()
    number_of_days = models.IntegerField()
    destination_country = CountryField(blank=True, null=True)
    reason = models.TextField(blank=True, null=True)

    class Meta:
        unique_together = [['country_name', 'user', 'exit_date']]

    # def __str__(self):
     #   return "%s %s %s" % (self.user, self.country_name, self.exit_date)


class TravelHistory(models.Model):

    # country_name = models.CharField(max_length=5, help_text='Select Country')
    country_name = CountryField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    entry_date = models.DateField()
    exit_date = models.DateField()

    class Meta:
        unique_together = [['country_name', 'user', 'entry_date']]

    def __str__(self):
        return "%s %s %s" % (self.user, self.country_name, self.entry_date)


class PRNotifications(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notification_type = models.TextField()
    email_date = models.DateField()
    email_sent = models.BooleanField(default=False)
    email_deleted = models.BooleanField(default=False)

    class Meta:
        unique_together = [['notification_type', 'user', 'email_date']]

    def __str__(self):
        return "%s %s %s %s" % (self.user, self.notification_type, self.email_date, self.email_sent)

pr_days_tracker/tracker_app/forms.py
from django import forms
from .models import User, UserCountryData, TravelData
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django_countries.widgets import CountrySelectWidget
from django_countries.fields import CountryField
from django.utils.safestring import mark_safe
from django_otp.plugins.otp_email.models import EmailDevice


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    password1 = None

    class Meta:
        model = User
        fields = ("email", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.is_active = False
        user.set_password(self.cleaned_data["password2"])
        if commit:
            user.save()
            my_group = Group.objects.get(name='Public Users')
            my_group.user_set.add(user)
            opt_device = EmailDevice()
            opt_device.user = user
            opt_device.name = "Email"
            opt_device.email = user.email
            opt_device.save()
        return user


class UserCountryForm(forms.ModelForm):
    class Meta:
        model = UserCountryData
        fields = ('entry_date', 'country_name', 'pr_date', 'notifications_on')
        widgets = {
            'entry_date': forms.DateInput(attrs={'placeholder': 'dd-mm-yyyy', 'autocomplete': 'off'}),
            'pr_date': forms.DateInput(attrs={'placeholder': 'dd-mm-yyyy', 'autocomplete': 'off'}),
            'notifications_on': forms.RadioSelect(
                choices=[
                    ('1', 'On'),
                    ('0', 'OFF'),
                ]
            )
        }

    def clean(self):
        cleaned_data = super().clean()
        entry_date = cleaned_data.get('entry_date')
        pr_date = cleaned_data.get('pr_date')
        if pr_date:
            if entry_date > pr_date:
                self.add_error('pr_date', "Entry date should be less than or equal to PR date")


class UserBasicData(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class TravelDatesForm(forms.ModelForm):
    reason = forms.CharField(required=False, label='Reason: Max 400 Characters', max_length=400,
                             widget=forms.Textarea(attrs={"rows": 3}))
    destination_country = CountryField(blank_label="Select Country").formfield(required=False,
                                                                               label=mark_safe(
                                                                                   'Destination Country <a class="text-primary" data-toggle="tooltip" data-placement="top" title="If you visited more than one country during the same absence, list the first country in \'Destination\' and list the other countries in the \'Reason\' field."> <i class="fa fa-info-circle fa-1x"></i></a>'))
    exit_date = forms.DateField(label='From',
                                widget=forms.DateInput(attrs={'placeholder': 'dd-mm-yyyy', 'autocomplete': 'off'}))
    entry_date = forms.DateField(label='To',
                                 widget=forms.DateInput(attrs={'placeholder': 'dd-mm-yyyy', 'autocomplete': 'off'}))

    class Meta:
        model = TravelData
        fields = ('entry_date', 'exit_date', 'country_name', 'destination_country', 'reason')

    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(TravelDatesForm, self).__init__(*args, **kwargs)
        self.fields['country_name'].required = False

    def clean(self):
        cleaned_data = super().clean()
        entry_date = cleaned_data.get('entry_date')
        exit_date = cleaned_data.get('exit_date')
        if entry_date < exit_date:
            # raise forms.ValidationError("Exit date should be less than or equal to entry date", code='invalid')
            self.add_error('entry_date', "Entry date should be greater than or equal to exit date")

pr_days_tracker/templates/profile/deactivate.html
{% extends 'home.html' %}
{% block title %} Deactivate Account {% endblock %}
{% block head_block %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'login.css' %}?v={{ context.SCRIPT_VERSION }}" xmlns="http://www.w3.org/1999/html"/>
    {% endblock %}
{% block body_block %}
<div class="wrapper fadeInDown">
    <div id="formContent" >
        {% if form.errors or message %}
        <div class="alert alert-danger" role="alert">
            {{ form.errors }}
            {{ message }}
        </div>
        {% endif %}
        <div class="login-form">
            <div class="text-left">
                <form id="deactivate-form" role="form" class="form" method="post">
                    {% csrf_token %}
                    <h2 class="text-center">Deactivate Account</h2>
                    <div class="form-group">
                        <div class="input-group">
                            <input id="confirm_input" name="confirm" placeholder="Type YES" class="form-control"  type="text" required">
                        </div>
                        <ul class="list-unstyled">
                            <li class="small">Please type <b>"YES"</b> to confirm and click deactivate (CASE SENSITIVE)</li>
                        </ul>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-lg btn-primary btn-block" value="Deactivate" type="submit">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pr_days_tracker/templates/profile/profile.html
{% extends 'home.html' %}
{% block title %} Profile {% endblock %}
{% block head_block %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'login.css' %}?v={{ context.SCRIPT_VERSION }}" xmlns="http://www.w3.org/1999/html"/>
{% endblock %}
{% block body_block %}
<div class="wrapper fadeInDown">
    <div id="formContent">
        {% if message %}
        {% if message.success %}
        <div class="alert alert-success" role="alert">
            {{ message.success | striptags }}
        </div>
        {% else %}
        <div class="alert alert-danger" role="alert">
            {{ message.pr_date | striptags }}
            {{ message.entry_date | striptags }}
            {{ message.non_field_errors }}
            {{ message.gen }}
        </div>
        {% endif %}
        {% endif %}
        <div class="login-form">
            <div class="text-left">
                <form id="profile-form" role="form" class="form" method="post">
                    {% csrf_token %}
                    <h2 class="text-center">Profile</h2>
                    <div class="form-group">
                        <div class="input-group">
                            <input id="first_name" name="first_name" placeholder="First Name" class="form-control"
                                   type="text" required value="{{user.first_name}}">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input id="last_name" name="last_name" placeholder="Last Name" class="form-control"
                                   type="text" required value="{{user.last_name}}">
                        </div>
                    </div>
                    {% include "country_select.html" %}
                    <div class="form-group">
                        <label for="id_entry_date">First Entry Date</label>
                        <a class="text-primary" data-toggle="tooltip" data-placement="top"
                           title="The day you entered the country for the first time.">
                            <i class="fa fa-info-circle fa-1x"></i>

                        </a>
                        <div class="input-group">
                            <input autocomplete="off" name="entry_date" aria-describedby="entry_date_help"
                                   placeholder="Entry Date" class="form-control" type="text" id="id_entry_date"
                                   required value="{{ data.entry_date|date:'Y-m-d'}}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_pr_date">Permanent Residence Date</label>
                        <a class="text-primary" data-toggle="tooltip" data-placement="top"
                           title="Enter the date you became a permanent resident of Canada (see Box 45 on your Record of Landing (IMM 1000), Box 46 on your Confirmation of Permanent Residence (IMM 5292 or IMM 5509) or the back of your Permanent Resident Card).">
                            <i class="fa fa-info-circle fa-1x"></i>

                        </a>
                        <div class="input-group">
                            <input autocomplete="off" name="pr_date" aria-describedby="pr_date_help"
                                   placeholder="PR Date" class="form-control" type="text" id="id_pr_date"
                                   value="{{ data.pr_date|date:'Y-m-d'}}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Reminders</label>
                        <a class="text-primary" data-toggle="tooltip" data-placement="top"
                           title="Regular notifications">
                            <i class="fa fa-info-circle fa-1x"></i>
                        </a>
                        <div class="input-group">
                        <label for="id_notifications_on_0">
                            <input required type="radio" name="notifications_on" value="1" id="id_notifications_on_0" {{ context.notifications_true }}>
                            On </label>
                        </div>
                        <div class="input-group">
                        <label for="id_notifications_on_1">
                            <input required type="radio" name="notifications_on" value="0" id="id_notifications_on_1"  {{ context.notifications_false }}>
                            OFF</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-lg btn-primary btn-block" value="Save" type="submit">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
$('#profile-form').on('submit', function() {
    $('#country_select').prop('disabled', false);
});


</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"
        integrity="sha256-bqVeqGdJ7h/lYPq6xrPv/YGzMEb6dNxlfiTUHSgRCp8=" crossorigin="anonymous"></script>
<script src="{% static 'profile.js'%}?v={{ context.SCRIPT_VERSION }} "></script>
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"
      integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous"/>
{% endblock %}